# Generated by Django 4.2 on 2024-01-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_auto_20221119_0255"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("link", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
            ],
        ),
    ]
